version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"  # Port pour l'interface de gestion
      - "5672:5672"    # Port par défaut de RabbitMQ

  app:
    build: .           # Construit à partir du Dockerfile dans ce dossier
    depends_on:
      - rabbitmq       # Assure que RabbitMQ est démarré avant d'exécuter l'application
    environment:
      - broker_host=rabbitmq  # Définit l'hôte pour RabbitMQ
