version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"  # Port pour l'interface de gestion
      - "5672:5672"    # Port par défaut de RabbitMQ

  producer:
    build: .           # Utilise le Dockerfile pour construire l'application
    environment:
      - broker_host=rabbitmq
    depends_on:
      - rabbitmq       # Assure que RabbitMQ est en cours d'exécution

  consumer:
    build: .           # Utilise le même Dockerfile
    environment:
      - broker_host=rabbitmq
    depends_on:
      - rabbitmq       # Assure que RabbitMQ est en cours d'exécution
    command: java capteurtempjava.Consumer # Lance le consommateur
