#!/bin/bash
if [ ! "$(command -v docker)" ]; then
    echo "docker could not be found"
    exit 0
fi

CURRENT_DIR=$(basename $(pwd))

NETWORK_NAME=mqtt-network

if [ ! "$(docker network ls | grep "$NETWORK_NAME")" ]; then
  echo "Creating network ..."
  docker network create $NETWORK_NAME
fi

docker run -d --rm -it \
    --name $CURRENT_DIR-mysql \
    -e MYSQL_ROOT_PASSWORD=rootpassword \
    -p 3306:3306 \
    --net $NETWORK_NAME \
    mysql:8.0

docker run -d --rm -it \
    --name $CURRENT_DIR-phpmyadmin \
    -p 8080:80 \
    --link $CURRENT_DIR-mysql:db \
    --net $NETWORK_NAME \
    phpmyadmin/phpmyadmin